/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package HotelUI;

import java.time.LocalDate;


/**
 *
 * @author Forge-15
 */
public class ViewInvoice extends javax.swing.JFrame {

    public ViewInvoice(String roomNumber, LocalDate dateIn, LocalDate dateOut, int dayOfStay, String invoiceID, LocalDate invoiceDate, String name, double totalAmount) {
        initComponents();
        setInvoice(roomNumber, dateIn, dateOut, dayOfStay, invoiceID, invoiceDate, name, totalAmount);
    }
    
    private void setInvoice(String roomNumber, LocalDate dateIn, LocalDate dateOut, int dayOfStay, String invoiceID, LocalDate invoiceDate, String name, double totalAmount) {
        lblRoomNumber.setText("Room Number: " + roomNumber);
        lblDateIn.setText("Date In: " + dateIn);
        lblDateOut.setText("Date Out: " + dateOut);
        lblNumberOfDay.setText("Day of Stay: " + dayOfStay);
        lblInvoiceDate.setText("Invoice Date: " + invoiceDate);
        lblInvoiceID.setText("Invoice ID: " + invoiceID);
        lblGuestName.setText("Guest Name: " + name);
        lblTA.setText("Total Amount: " + totalAmount);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInvoicePage = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        lblRoomNumber = new javax.swing.JLabel();
        lblDateIn = new javax.swing.JLabel();
        lblDateOut = new javax.swing.JLabel();
        lblGuestName = new javax.swing.JLabel();
        lblTA = new javax.swing.JLabel();
        lblNumberOfDay = new javax.swing.JLabel();
        lblInvoiceID = new javax.swing.JLabel();
        lblInvoiceDate = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        btnBackToHome = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel25.setText("Invoice");

        lblRoomNumber.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblRoomNumber.setText("Room Number: 1A");

        lblDateIn.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDateIn.setText("Date In: DD/MM/YYYY");

        lblDateOut.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDateOut.setText("Date Out: DD/MM/YYYY");

        lblGuestName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGuestName.setText("Guest Name: John ");

        lblTA.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTA.setText("Total Amount: RM1000.00");

        lblNumberOfDay.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNumberOfDay.setText("Number of Day: 3");

        lblInvoiceID.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInvoiceID.setText("Invoice ID: 123");

        lblInvoiceDate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblInvoiceDate.setText("Invoice Date: DD/MM/YYYY");

        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        btnBackToHome.setText("Back to Home");
        btnBackToHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToHomeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInvoicePageLayout = new javax.swing.GroupLayout(pnlInvoicePage);
        pnlInvoicePage.setLayout(pnlInvoicePageLayout);
        pnlInvoicePageLayout.setHorizontalGroup(
            pnlInvoicePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoicePageLayout.createSequentialGroup()
                .addGroup(pnlInvoicePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInvoicePageLayout.createSequentialGroup()
                        .addGap(390, 390, 390)
                        .addComponent(jLabel25))
                    .addGroup(pnlInvoicePageLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(pnlInvoicePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNumberOfDay)
                            .addComponent(lblRoomNumber)
                            .addComponent(lblDateIn)
                            .addComponent(lblDateOut))
                        .addGap(171, 171, 171)
                        .addGroup(pnlInvoicePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTA)
                            .addComponent(lblGuestName)
                            .addComponent(lblInvoiceDate)
                            .addComponent(lblInvoiceID))))
                .addContainerGap(169, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlInvoicePageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBackToHome)
                .addGap(35, 35, 35))
        );
        pnlInvoicePageLayout.setVerticalGroup(
            pnlInvoicePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInvoicePageLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(pnlInvoicePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlInvoicePageLayout.createSequentialGroup()
                        .addComponent(lblInvoiceID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblInvoiceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblGuestName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblTA, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlInvoicePageLayout.createSequentialGroup()
                        .addComponent(lblRoomNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDateIn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDateOut, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumberOfDay, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, Short.MAX_VALUE)
                .addGroup(pnlInvoicePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBackToHome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 922, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInvoicePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(pnlInvoicePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        System.out.println("Print");
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnBackToHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToHomeActionPerformed

        this.dispose();
    }//GEN-LAST:event_btnBackToHomeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackToHome;
    private javax.swing.JButton btnPrint;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel lblDateIn;
    private javax.swing.JLabel lblDateOut;
    private javax.swing.JLabel lblGuestName;
    private javax.swing.JLabel lblInvoiceDate;
    private javax.swing.JLabel lblInvoiceID;
    private javax.swing.JLabel lblNumberOfDay;
    private javax.swing.JLabel lblRoomNumber;
    private javax.swing.JLabel lblTA;
    private javax.swing.JPanel pnlInvoicePage;
    // End of variables declaration//GEN-END:variables
}
